services:
    lightsaml.credential.credential_store:
        class: LightSaml\Store\Credential\CompositeCredentialStore
        factory: [@lightsaml.credential.credential_store_factory, build]
        arguments:
            - @lightsaml.party.idp_entity_descriptor_store
            - @lightsaml.party.sp_entity_descriptor_store
            - "@=service('lightsaml.own.credential_store').getByEntityId(parameter('lightsaml.own.entity_id'))"
            - []

    lightsaml.credential.credential_store_factory:
        class: LightSaml\Store\Credential\Factory\CredentialFactory
