services:
    lightsaml.credential.credential_store:
        class: LightSaml\Store\Credential\CompositeCredentialStore
        factory: [LightSaml\SymfonyBridgeBundle\Factory\CredentialStoreFactory, build]
        arguments:
            - @lightsaml.party.idp_entity_descriptor_store
            - @lightsaml.party.sp_entity_descriptor_store
            - %lightsaml.own.entity_id%
            - @lightsaml.own.credential_store
            - []

    lightsaml.credential.credential_store_factory:
        class: LightSaml\Store\Credential\Factory\CredentialFactory
