parameters:
    lightsaml.own.entity_id: ~
    lightsaml.route.login_check: lightsaml.login_check

services:
    lightsaml.own.credential_store:
        class: LightSaml\Store\Credential\CompositeCredentialStore

    lightsaml.own.entity_descriptor_provider:
        class: LightSaml\Builder\EntityDescriptor\SimpleEntityDescriptorBuilder
        factory: [LightSaml\SymfonyBridgeBundle\Factory\OwnEntityDescriptorProviderFactory, build]
        arguments:
            - %lightsaml.own.entity_id%
            - @router
            - %lightsaml.route.login_check%
            - ~
            - @lightsaml.own.credential_store
