services:
    lightsaml.provider.attribute_value:
        class: LightSaml\Provider\Attribute\AttributeValueProviderInterface

    lightsaml.provider.attribute_name:
        class: LightSaml\Provider\Attribute\AttributeNameProviderInterface

    lightsaml.provider.session_info:
        class: LightSaml\Provider\Attribute\SessionInfoProviderInterface

    lightsaml.provider.name_id:
        class: LightSaml\Provider\NameID\NameIdProviderInterface
